### ISSUE TITLE
Support for X-Bz-Test-Mode headers

### ISSUE THREAD

**Issue by brycied00d** [fog/fog-backblaze#16]
Backblaze's B2 API supports an optional HTTP request header during API transactions, `X-Bz-Test-Mode`. By setting this header to certain specific values, a developer is able to trigger intermittent failures at different stages in a session, enabling deeper testing of their error handling.

https://www.backblaze.com/b2/docs/integration_checklist.html

**Comment by Paxa** [comment]
Added `connection.options[:headers]`
