### ISSUE TITLE
 undefined method `parse' 

### ISSUE THREAD

**Issue by fameoflight** [fog/fog-backblaze#5]
I am trying to use the sample code 

```pp connection.put_object("fog-smoke-test", "my file", "THISISATESTFILE").json```

but it keep throwing 

```
NoMethodError: undefined method `parse' for Fog::JSON:Module
Did you mean?  parent
from ~/.rvm/gems/ruby-2.5.1/gems/fog-backblaze-0.1.1/lib/fog/backblaze/json_response.rb:12:in `json'
``

**Comment by Paxa** [comment]
Hi, sorry for late response.

I fixed it and release a new version. Running `bundle update fog-backblaze` should solve this
