### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by dan** [fog/fog-backblaze#8]
It seems that there's a newish depreciation warning with the latest Fog.

```
[fog][DEPRECATION] Unable to load Fog::Backblaze::Storage
[fog][DEPRECATION] The format Fog::Storage::Backblaze is deprecated
```

**Comment by Paxa** [comment]
Fixed in master 👍

**Comment by mrmason** [comment]
Hi @Paxa - is there a reason why this isn't released up as a new version on rubygems yet ?
